from .state import AgentState
from .utils.logger import logger
import json

class CriticNode:
    """
    The 'Senior Architect' node. 
    It reviews code generated by the CoderNode and 'Wisdom Nuggets' from the Evolver.
    It rejects poor implementation or risky code before it's merged.
    """
    def __init__(self, model):
        self.model = model

    def __call__(self, state: AgentState):
        if not state.get('missing_tool') or not state['missing_tool'].startswith("REPAIR:") and not state.get('reflection'):
             return state

        logger.info("Senior Architect: Reviewing generated architecture for integrity...")
        
        # We need context: What was the goal and what is the current proposed fix/tool?
        review_prompt = f"""
        You are the 'Senior Architect' of Agentic OS. 
        Your job is to CRITIQUE the following proposed system changes to ensure elite quality.
        
        GOAL: {state['goal']}
        REFLECTION: {state['reflection']}
        PROPOSED CHANGE/TOOL: {state['missing_tool']}
        
        CRITERIA:
        1. Security: Is there any dangerous or poorly handled code?
        2. Efficiency: Is the implementation optimal for a Neural OS?
        3. Reliability: Does it include error handling?
        
        If the quality is POOR, provide a single 'REJECTION_FEEDBACK' and set 'passed' to false.
        Otherwise, set 'passed' to true.
        
        Return ONLY a JSON object:
        {{
            "passed": true/false,
            "rejection_feedback": "If passed is false, why? What needs to be fixed?",
            "grade": "A-E"
        }}
        """
        
        try:
            response = self.model.invoke(review_prompt).content.strip()
            if "```" in response: response = response.split("```")[1].strip("json\n ")
            data = json.loads(response)
            
            if not data.get("passed"):
                logger.warning(f"Senior Architect: REJECTED Change. Feedback: {data['rejection_feedback']}")
                # Reset missing_tool so Coder has to try again or we handle the loop
                state['reflection'] = f"REJECTED by Architect: {data['rejection_feedback']}"
                state['status'] = "failed_review"
            else:
                logger.info(f"Senior Architect: APPROVED (Grade: {data.get('grade')})")
                
        except Exception as e:
            logger.error(f"Critic Node failed: {e}")
            
        return state
